import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const out = path.join(ROOT, 'dist');
const read = p => JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));
const site = read('data/site.json');
const categories = read('data/categories.json');
const articles = read('data/articles.json').sort((a,b)=>new Date(b.published)-new Date(a.published));
const images = read('data/images.json');
const catBySlug = Object.fromEntries(categories.map(c=>[c.slug,c]));
fs.rmSync(out,{recursive:true,force:true}); fs.mkdirSync(out,{recursive:true});
fs.cpSync(path.join(ROOT,'public'),out,{recursive:true});
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=d=>new Intl.DateTimeFormat('bg-BG',{dateStyle:'long',timeZone:'Europe/Sofia'}).format(new Date(d));
const url=p=>site.url+(p==='/'?'':p);
function head({title,description,canonical='/',image,article}){
 const fullTitle = title ? `${title} | ${site.name}` : `${site.name} — ${site.tagline}`;
 const img=image ? images[image]?.url : images['solar-roof'].url;
 const robots='index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1';
 let jsonld = {"@context":"https://schema.org","@type":"WebSite","name":site.name,"url":site.url,"inLanguage":"bg-BG","publisher":{"@type":"Organization","name":site.publisher,"url":site.url}};
 if(article) jsonld={"@context":"https://schema.org","@type":"NewsArticle","headline":article.title,"description":article.description,"datePublished":article.published,"dateModified":article.updated,"mainEntityOfPage":url('/'+article.slug),"image":[img],"author":{"@type":"Organization","name":"Редакционен екип Photovoltaic Bulgaria","url":url('/redaktsiya')},"publisher":{"@type":"Organization","name":site.publisher,"url":site.url},"inLanguage":"bg-BG"};
 return `<!doctype html><html lang="bg"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(fullTitle)}</title><meta name="description" content="${esc(description||site.description)}"><meta name="robots" content="${robots}"><link rel="canonical" href="${url(canonical)}"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:title" content="${esc(fullTitle)}"><meta property="og:description" content="${esc(description||site.description)}"><meta property="og:url" content="${url(canonical)}"><meta property="og:image" content="${img}"><meta property="og:locale" content="bg_BG"><meta name="twitter:card" content="summary_large_image"><link rel="alternate" type="application/rss+xml" title="${site.name}" href="${url('/rss.xml')}"><link rel="stylesheet" href="/assets/style.css"><script type="application/ld+json">${JSON.stringify(jsonld)}</script></head><body>`;
}
function nav(){return `<header class="top"><div class="wrap nav"><a class="brand" href="/"><span class="brandmark"></span><span>Photovoltaic Bulgaria<small>Енергия за дома</small></span></a><nav class="navlinks">${categories.map(c=>`<a href="/kategoriya/${c.slug}">${c.name}</a>`).join('')}<a href="/kalculator">Калкулатор</a><a href="/redaktsiya">Редакция</a></nav><button class="btn mobile-menu" data-menu aria-label="Меню">Меню</button></div></header>`}
function footer(){return `<footer class="footer"><div class="wrap footergrid"><div><strong>${site.name}</strong><p>${site.description}</p><p>© 2026 Photovoltaic Bulgaria. Независима информационна медия.</p></div><div><strong>За читателя</strong><a href="/redaktsiya">Редакция и методология</a><a href="/korrektsii">Политика за корекции</a><a href="/kontakt">Контакт</a></div><div><strong>Правни</strong><a href="/poveritelnost">Поверителност</a><a href="/usloviya">Условия</a><a href="/rss.xml">RSS</a><a href="/news-sitemap.xml">News Sitemap</a></div></div></footer><script src="/assets/app.js" defer></script></body></html>`}
function card(a,lead=false){const im=images[a.image], c=catBySlug[a.category];return `<article class="card"><a href="/${a.slug}"><div class="card-media"><img src="${im.url}" alt="${esc(im.alt)}" loading="${lead?'eager':'lazy'}" ${lead?'fetchpriority="high"':''}></div><div class="card-body"><div class="meta"><span class="pill">${c.emoji} ${c.name}</span>${a.kind==='news'?'<span class="news-badge">НОВО</span>':''}<span>${fmt(a.published)}</span></div><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p></div></a></article>`}
function mini(a){const c=catBySlug[a.category];return `<a class="mini" href="/${a.slug}"><div class="meta"><span>${c.emoji} ${c.name}</span><span>•</span><span>${fmt(a.published)}</span></div><h3>${esc(a.title)}</h3></a>`}
function write(rel,html){const p=path.join(out,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,html)}
function shell(content,meta={}){return head(meta)+nav()+content+footer()}
const lead=articles[0], side=articles.slice(1,4), rest=articles.slice(1);
write('index.html', shell(`<main><section class="hero"><div class="wrap"><span class="kicker">● Независима енергийна медия за България</span><h1>По-ниска сметка.<br><span>По-умен дом.</span></h1><p>Фотоволтаици, батерии, термопомпи, обновяване и помощи — обяснени с числа, първични източници и без рекламни обещания.</p><div class="hero-actions"><a class="btn primary" href="/${lead.slug}">Последен анализ →</a><a class="btn" href="/redaktsiya">Как проверяваме фактите</a></div></div></section><div class="ticker"><div class="wrap"><strong>ДНЕС:</strong> Следим решенията на КЕВР, програмите за обновяване, цените на енергията и новите технологии за дома.</div></div><section class="section"><div class="wrap"><div class="section-head"><div><h2>Водещо</h2><p>Практична информация с директни източници.</p></div></div><div class="lead-grid">${card(lead,true)}<div class="side-list">${side.map(mini).join('')}<div class="adslot">Рекламна позиция — активира се след одобрение от AdSense</div></div></div></div></section><section class="section"><div class="wrap"><div class="section-head"><h2>Избери тема</h2></div><div class="cats">${categories.map(c=>`<a class="cat" href="/kategoriya/${c.slug}"><b>${c.emoji}</b><h3>${c.name}</h3><p>${c.desc}</p></a>`).join('')}</div></div></section><section class="section"><div class="wrap"><div class="section-head"><h2>Нови анализи</h2><p>SEO ръководства + актуални новини</p></div><div class="grid3">${rest.slice(0,6).map(a=>card(a)).join('')}</div></div></section><section class="section"><div class="wrap trust"><div class="trustbox"><h3>Първо източникът, после заглавието</h3><p>Регулаторни решения, помощи и правила се проверяват срещу първични институционални източници. Когато има несигурност, я отбелязваме.</p></div><div class="trustbox"><h3>Автоматизация с човешки стандарти</h3><p>Системата може да открива теми и да подготвя публикации, но блокира дублиране, неподкрепени твърдения и съдържание без добавена стойност.</p></div></div></section></main>`,{canonical:'/'}));
for(const c of categories){const list=articles.filter(a=>a.category===c.slug);write(`kategoriya/${c.slug}/index.html`,shell(`<main class="page"><div class="wrap"><span class="kicker">${c.emoji} Тема</span><h1>${c.name}</h1><p>${c.desc}</p><div class="grid3" style="margin-top:28px">${list.map(a=>card(a)).join('')||'<p>Подготвяме първите материали.</p>'}</div></div></main>`,{title:c.name,description:c.desc,canonical:`/kategoriya/${c.slug}`}));}
for(const a of articles){const im=images[a.image],c=catBySlug[a.category];const srcs=a.sources.map(s=>`<li><a href="${s.url}" rel="nofollow noopener" target="_blank">${esc(s.label)}</a></li>`).join('');write(`${a.slug}/index.html`,shell(`<main><section class="article-hero"><div class="wrap"><div class="meta"><span class="pill">${c.emoji} ${c.name}</span>${a.kind==='news'?'<span class="news-badge">АКТУАЛНО</span>':''}<span>${fmt(a.published)}</span><span>•</span><span>Редакционен екип</span></div><h1>${esc(a.title)}</h1><p class="dek">${esc(a.description)}</p></div></section><div class="wrap"><div class="article-cover"><img src="${im.url}" alt="${esc(im.alt)}" fetchpriority="high"></div><div class="credit">Снимка: ${esc(im.credit)}</div></div><div class="wrap article-layout"><article class="prose">${a.body.map((p,i)=>`${i===2?'<h2>Какво означава това на практика</h2>':''}<p>${esc(p)}</p>`).join('')}<div class="sourcebox"><h2>Източници</h2><ul>${srcs}</ul><p><small>Материалът е информационен и не представлява индивидуална финансова, правна или техническа консултация.</small></p></div></article><aside class="aside"><div class="asidebox"><h3>Нашият стандарт</h3><ul><li>Първични източници при правила и цени</li><li>Ясно разграничение между факт и оценка</li><li>Дата на публикация и актуализация</li><li>Корекции при нови данни</li></ul></div><div class="adslot">Рекламна позиция</div></aside></div></main>`,{title:a.title,description:a.description,canonical:`/${a.slug}`,image:a.image,article:a}));}
const pages={
 'redaktsiya':{t:'Редакция и методология',d:'Кои сме ние и как работим.',b:`<p>Photovoltaic Bulgaria е независим информационен проект за енергията в дома. Публикуваме практически ръководства и актуални материали за български читатели.</p><h2>Как работим</h2><p>При цени, нормативни решения, помощи и публични програми предпочитаме първични източници: КЕВР, български министерства и агенции, Европейската комисия и официални документи. Вторични медийни източници използваме за контекст, а не като единствена основа за важни твърдения.</p><h2>Автоматизация</h2><p>Използваме автоматизирани инструменти за мониторинг, структуриране на източници и подготовка на чернови. Публикация се допуска само ако премине проверки за източници, дублиране, конкретност и добавена стойност. Не публикуваме автоматично текст само за да достигнем дневна квота.</p><h2>Авторство</h2><p>Материалите, създавани от редакционния процес, са подписани от „Редакционен екип Photovoltaic Bulgaria“. При включване на конкретни външни експерти ще посочваме имената и компетентността им.</p>`},
 'korrektsii':{t:'Политика за корекции',d:'Как поправяме неточности.',b:`<p>Ако открием фактическа грешка, я коригираме възможно най-бързо и актуализираме датата на материала. При съществена промяна в изводите добавяме бележка за корекция. Източник, който е бил заменен от по-нова официална версия, се актуализира.</p><p>Сигнали могат да се изпращат на <a href="mailto:${site.email}">${site.email}</a>.</p>`},
 'kontakt':{t:'Контакт',d:'Свържете се с редакцията.',b:`<p>Редакционни сигнали, предложения за теми и искания за корекции: <a href="mailto:${site.email}">${site.email}</a>.</p><p>Не изпращайте лични финансови данни, ЕГН, номера на договори или друга чувствителна информация.</p>`},
 'poveritelnost':{t:'Политика за поверителност',d:'Основна информация за данните.',b:`<p>Сайтът е проектиран да работи без задължителна регистрация. При бъдещо активиране на аналитика, реклама или бюлетин тази страница ще бъде актуализирана с конкретните доставчици, цели, срокове за съхранение и механизми за съгласие, приложими за ЕС.</p>`},
 'usloviya':{t:'Условия за ползване',d:'Информационен характер на съдържанието.',b:`<p>Съдържанието е с общ информационен характер. То не е персонализирана финансова, правна, инженерна или инвестиционна препоръка. Преди договор, строителна работа или инвестиция проверете официалните правила и потърсете квалифициран специалист, когато това е необходимо.</p>`}
};
for(const [slug,p] of Object.entries(pages)) write(`${slug}/index.html`,shell(`<main class="page"><div class="wrap"><span class="kicker">Photovoltaic Bulgaria</span><h1>${p.t}</h1>${p.b}</div></main>`,{title:p.t,description:p.d,canonical:`/${slug}`}));
write('kalculator/index.html',shell(`<main class="page"><div class="wrap"><span class="kicker">☀️ Инструмент</span><h1>Соларен калкулатор за дома</h1><p>Бърза ориентировъчна оценка за мощност, брой панели и годишно производство. Данните не заменят технически проект.</p><form id="solarCalc" class="trustbox" style="max-width:850px;margin-top:24px"><div class="calcform"><label>Годишно потребление (kWh)<input name="annual" type="number" min="500" value="6000" required></label><label>Свободна площ на покрива (m²)<input name="area" type="number" min="5" value="45" required></label><label>Специфичен добив (kWh/kWp/год.)<input name="yield" type="number" min="700" max="1800" value="1300"></label><label>Мощност на панел (W)<input name="panel" type="number" min="250" max="700" value="450"></label><label>Очаквано собствено потребление (%)<input name="self" type="number" min="10" max="100" value="55"></label></div><button class="btn primary" type="submit" style="margin-top:18px">Изчисли</button></form><div id="calcOut" class="trustbox" style="max-width:850px;margin-top:16px"><p>Въведете данните и натиснете „Изчисли“.</p></div><script src="/assets/calculator.js" defer></script></div></main>`,{title:'Соларен калкулатор',description:'Ориентировъчен калкулатор за домашна фотоволтаична система в България.',canonical:'/kalculator'}));
const sm = [`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,`<url><loc>${site.url}/</loc><changefreq>daily</changefreq><priority>1.0</priority></url>`,...categories.map(c=>`<url><loc>${site.url}/kategoriya/${c.slug}</loc><changefreq>daily</changefreq><priority>0.8</priority></url>`),...articles.map(a=>`<url><loc>${site.url}/${a.slug}</loc><lastmod>${a.updated.slice(0,10)}</lastmod><changefreq>weekly</changefreq><priority>0.9</priority></url>`),`</urlset>`].join('');write('sitemap.xml',sm);
const recent=articles.filter(a=>Date.now()-new Date(a.published).getTime()<=2*864e5);
const ns=[`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">`,...recent.map(a=>`<url><loc>${site.url}/${a.slug}</loc><news:news><news:publication><news:name>${site.name}</news:name><news:language>bg</news:language></news:publication><news:publication_date>${a.published}</news:publication_date><news:title>${esc(a.title)}</news:title></news:news></url>`),`</urlset>`].join('');write('news-sitemap.xml',ns);
const rss=`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${site.name}</title><link>${site.url}</link><description>${esc(site.description)}</description><language>bg-bg</language>${articles.slice(0,20).map(a=>`<item><title>${esc(a.title)}</title><link>${site.url}/${a.slug}</link><guid>${site.url}/${a.slug}</guid><pubDate>${new Date(a.published).toUTCString()}</pubDate><description>${esc(a.description)}</description></item>`).join('')}</channel></rss>`;write('rss.xml',rss);
write('robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${site.url}/sitemap.xml\nSitemap: ${site.url}/news-sitemap.xml\n`);
write('llms.txt',`# ${site.name}\n\nIndependent Bulgarian publication about home energy, solar, batteries, heat pumps, renovation, subsidies and energy bills.\n\nEditorial policy: ${site.url}/redaktsiya\nRSS: ${site.url}/rss.xml\n`);
console.log(`Built ${articles.length} articles, ${categories.length} categories.`);
