import http from 'node:http';
import fs from 'node:fs';
import {randomUUID} from 'node:crypto';
import {publishPacket,appendLedger} from './autopublish/engine.mjs';
const PORT=Number(process.env.PORT||3000),cache=new Map();
const autopublishCfg=JSON.parse(fs.readFileSync(new URL('./autopublish/sites.json',import.meta.url),'utf8'));
async function jsonBody(req){let size=0,chunks=[];for await(const ch of req){size+=ch.length;if(size>2_000_000)throw Error('payload_too_large');chunks.push(ch)}const raw=Buffer.concat(chunks).toString('utf8');return raw?JSON.parse(raw):{}}
function json(res,status,data){res.statusCode=status;res.setHeader('content-type','application/json');res.end(JSON.stringify(data))}
function publicSiteConfig(x){return {id:x.id,name:x.name,domain:x.domain,adapter:x.adapter,configured:x.configured===true,autoPublishWhenGreen:x.autoPublishWhenGreen===true,quality:x.quality}}

const sites=[
{id:'betgpt',name:'BetGPT',domain:'betgpt.live',keys:['football','match','ligue','champions','équipe','joueur','score','résultat','coupe']},
{id:'freehotels',name:'FreeHotels',domain:'freehotels.info',keys:['voyage','hôtel','hotel','tourisme','destination','vol','train','aéroport','plage','vacances']},
{id:'pulsoplaneta',name:'PulsoPlaneta',domain:'pulsoplaneta.es',keys:['tecnología','consumo','actualidad','sociedad','móvil','internet','empleo','dinero','viajes','salud']}
];
const dec=s=>(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const tag=(x,n)=>{const m=x.match(new RegExp('<'+n+'(?:\\s[^>]*)?>([\\s\\S]*?)<\\/'+n+'>','i'));return m?dec(m[1]):''};
async function get(url){const h=cache.get(url);if(h&&Date.now()-h.t<300000)return h.x;const c=new AbortController(),tm=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 ASTRA-News-Radar/0.1'},signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);const x=await r.text();cache.set(url,{t:Date.now(),x});return x}finally{clearTimeout(tm)}}
const parse=(xml,k)=>[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map((m,i)=>{const r=m[1];return{id:k+'-'+i,title:tag(r,'title'),source:tag(r,'source')||tag(r,'ht:news_item_source'),link:tag(r,'link')||tag(r,'ht:news_item_url'),date:tag(r,'pubDate'),traffic:tag(r,'ht:approx_traffic')}}).filter(x=>x.title);
const stop=new Set('le la les de des du un une et en au aux pour sur avec dans par est sont ce ces cette son sa ses qui que quoi dont ou se il elle ils elles plus moins tres vers apres avant tout tous toute toutes the a an and of to in on for with from is are was were this that these those as at by'.split(' '));
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const toks=s=>norm(s).split(/\s+/).filter(w=>w.length>2&&!stop.has(w));
function sim(a,b){const A=new Set(toks(a)),B=new Set(toks(b));if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(1,Math.min(A.size,B.size))}
const fresh=d=>{const t=new Date(d).getTime();if(!Number.isFinite(t))return 20;const h=Math.max(0,(Date.now()-t)/36e5);return h<1?100:h<3?90:h<6?80:h<12?65:h<24?50:h<48?30:10};
function fit(title,s){const h=norm(title);return Math.min(100,s.keys.filter(k=>h.includes(norm(k))).length*28)}
function traffic(v=''){const m=v.match(/[\d,.]+/),n=m?Number(m[0].replace(/[,.]/g,'')):0,x=n*(/m/i.test(v)?1e6:/k/i.test(v)?1e3:1);return x>=5e5?100:x>=1e5?90:x>=5e4?80:x>=1e4?65:x>=5e3?50:x?35:0}
function clusters(items){const out=[];for(const it of items){let b=null,bs=0;for(const c of out){const s=sim(it.title,c.title);if(s>bs){b=c;bs=s}}if(b&&bs>=.42)b.items.push(it);else out.push({title:it.title,date:it.date,items:[it]})}return out}
function angle(x,s,n){if(s.id==='betgpt')return 'Impact sportif concret, chiffres clés, calendrier/score et conséquence pour les prochains matchs, sans répéter les '+n+' sources déjà présentes.';if(s.id==='freehotels')return 'Conséquences pratiques pour les voyageurs : prix, dates, lieux, alternatives et tableau utile, avec sources primaires.';if(s.id==='pulsoplaneta')return 'Explicar qué cambia para el lector, datos verificables, contexto local y preguntas que los primeros artículos todavía no resuelven.';return 'Chercher la conséquence concrète ou l’information encore absente des premiers articles.'}
async function scan(country='FR',lang='fr',site='all'){
 const ceid=country+':'+lang,urls=['https://news.google.com/rss?hl='+encodeURIComponent(lang)+'&gl='+country+'&ceid='+encodeURIComponent(ceid),'https://trends.google.com/trending/rss?geo='+country];
 const z=await Promise.allSettled(urls.map(get)),err=[];const news=z[0].status==='fulfilled'?parse(z[0].value,'news'):(err.push('Google News: '+(z[0].reason?.message||'échec')),[]),tr=z[1].status==='fulfilled'?parse(z[1].value,'trend'):(err.push('Google Trends: '+(z[1].reason?.message||'échec')),[]),rows=[];
 for(const c of clusters(news)){const src=[...new Set(c.items.map(i=>i.source).filter(Boolean))],trend=tr.find(t=>sim(t.title,c.title)>=.34);for(const s of sites.filter(x=>site==='all'||x.id===site)){const f=fit(c.title,s);if(site==='all'&&!f)continue;const fr=fresh(c.date),sat=Math.min(100,c.items.length*16+src.length*8),ts=trend?Math.max(55,traffic(trend.traffic)):0,score=Math.round(Math.min(100,fr*.30+f*.30+ts*.22+Math.min(100,src.length*18)*.10+Math.max(0,100-sat)*.08));rows.push({score,title:c.title,site:s,evidence:trend?'NEWS + TREND SIGNAL':'CONFIRMED NEWS',discoverSignal:Math.round(Math.min(99,score*.82+f*.12)),freshness:fr,fit:f,trendScore:ts,sources:src.length||c.items.length,date:c.date,traffic:trend?.traffic||'',trend:trend?.title||'',angle:angle(c.title,s,src.length||c.items.length),action:score>=80?'PUBLIER':score>=65?'PRÉPARER':score>=50?'SURVEILLER':'IGNORER',links:c.items.slice(0,3).map(i=>({source:i.source,title:i.title,link:i.link}))})}}
 return{generatedAt:new Date().toISOString(),newsCount:news.length,trendCount:tr.length,errors:err,opportunities:rows.sort((a,b)=>b.score-a.score).slice(0,80)}
}
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const html=`<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ASTRA NEWS RADAR</title><style>
:root{--b:#071019;--p:#0d1823;--l:#203347;--t:#edf6ff;--m:#8da4b9;--g:#49e19a;--a:#ffc766;--c:#4fd9ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#0d2740 0,transparent 32%),var(--b);color:var(--t);font:15px/1.45 system-ui,sans-serif}.s{max-width:1400px;margin:auto;padding:26px}header{display:flex;justify-content:space-between;gap:20px}h1{font-size:clamp(30px,5vw,56px);margin:6px 0;letter-spacing:-.04em}.ey{font-size:11px;color:var(--c);letter-spacing:.18em;font-weight:900}p{color:var(--m)}.ctrl,.met{display:grid;gap:12px;margin:18px 0}.ctrl{grid-template-columns:repeat(3,1fr) auto;background:var(--p);padding:14px;border:1px solid var(--l);border-radius:18px}.ctrl label{font-size:12px;color:var(--m)}select,button{width:100%;margin-top:5px;padding:11px;border-radius:10px;border:1px solid var(--l);background:#07131e;color:var(--t)}button{background:linear-gradient(135deg,#2456ff,#0ea5c6);font-weight:800;cursor:pointer}.met{grid-template-columns:repeat(4,1fr)}.met div{background:var(--p);border:1px solid var(--l);border-radius:15px;padding:15px}.met span{display:block;color:var(--m);font-size:12px}.met b{font-size:25px}.note{padding:12px 14px;background:#09141e;border:1px solid var(--l);border-radius:14px;color:var(--m);font-size:12px}.list{margin-top:16px;border:1px solid var(--l);border-radius:18px;overflow:hidden}.opp{display:grid;grid-template-columns:76px 1fr;gap:14px;padding:18px;border-bottom:1px solid #17293a}.opp:last-child{border:0}.score{width:62px;height:62px;border-radius:16px;display:grid;place-items:center;background:#09141e;border:1px solid var(--l);font-size:23px;font-weight:900}.hot .score{border-color:var(--g)}.meta{display:flex;flex-wrap:wrap;gap:7px;color:var(--m);font-size:11px}.badge{padding:3px 7px;border-radius:999px;border:1px solid #2f5b4b;color:var(--g)}.amb{color:var(--a);border-color:#66552d}.opp h3{margin:6px 0;font-size:20px}.angle{margin:0 0 8px}.stats{display:flex;flex-wrap:wrap;gap:12px;color:var(--m);font-size:12px}.err{padding:14px;color:#ff9aa4}.src a{display:block;color:#87d9ff;font-size:12px;text-decoration:none;margin-top:5px}footer{text-align:center;color:#516b82;padding:22px;font-size:11px;letter-spacing:.12em}@media(max-width:750px){.s{padding:14px}.ctrl,.met{grid-template-columns:1fr 1fr}.ctrl button{grid-column:1/-1}}@media(max-width:500px){.ctrl,.met{grid-template-columns:1fr}.ctrl button{grid-column:auto}.opp{grid-template-columns:52px 1fr}.score{width:48px;height:48px;font-size:18px}}
</style></head><body><div class="s"><header><div><div class="ey">MYTHOS ASTRA Ω · EVIDENCE-FIRST</div><h1>ASTRA NEWS RADAR</h1><p>Radar mutualisé pour tous les sites Google News / Discover : détection, clustering, score et angle original.</p></div><div id="live">● LIVE</div></header><div class="ctrl"><label>Pays<select id="country"><option>FR</option><option>ES</option><option>BE</option><option>CH</option><option>DE</option><option>IT</option><option>US</option><option>GB</option></select></label><label>Langue<select id="lang"><option>fr</option><option>es</option><option>en</option><option>de</option><option>it</option></select></label><label>Site<select id="site"><option value="all">Tous</option>${sites.map(s=>'<option value="'+s.id+'">'+s.name+' · '+s.domain+'</option>').join('')}</select></label><button id="go">Scanner</button></div><div class="met"><div><span>Articles News</span><b id="n">—</b></div><div><span>Tendances</span><b id="t">—</b></div><div><span>Opportunités ≥80</span><b id="h">—</b></div><div><span>Dernier scan</span><b id="d">—</b></div></div><div class="note"><b>CONFIRMED NEWS</b> = observé dans Google News. <b>DISCOVER SIGNAL</b> = estimation éditoriale seulement. <b>CONFIRMED DISCOVER</b> sera réservé aux données Search Console de nos propres domaines.</div><div id="e"></div><div id="list" class="list"><div class="err">Scan en cours…</div></div><footer>OBSERVE → CLUSTER → SCORE → MATCH SITE → ANGLE → PUBLISH → MEASURE → LEARN</footer></div><script>
const q=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));async function go(){q('#go').disabled=true;q('#list').innerHTML='<div class="err">Collecte Google News + Google Trends…</div>';try{const p=new URLSearchParams({country:q('#country').value,lang:q('#lang').value,site:q('#site').value}),r=await fetch('/api/opportunities?'+p),x=await r.json();q('#n').textContent=x.newsCount;q('#t').textContent=x.trendCount;q('#h').textContent=x.opportunities.filter(o=>o.score>=80).length;q('#d').textContent=new Date(x.generatedAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});q('#e').innerHTML=x.errors.length?'<div class="err">Mode dégradé : '+E(x.errors.join(' · '))+'</div>':'';q('#list').innerHTML=x.opportunities.length?x.opportunities.map(o=>'<article class="opp '+(o.score>=80?'hot':'')+'"><div class="score">'+o.score+'</div><div><div class="meta"><span>'+E(o.site.name)+'</span><span class="badge">'+E(o.evidence)+'</span>'+(o.discoverSignal>=70?'<span class="badge amb">DISCOVER SIGNAL '+o.discoverSignal+'</span>':'')+'<span>'+E(o.action)+'</span></div><h3>'+E(o.title)+'</h3><p class="angle">'+E(o.angle)+'</p><div class="stats"><span>Fraîcheur <b>'+o.freshness+'</b></span><span>Fit <b>'+o.fit+'</b></span><span>Trend <b>'+o.trendScore+'</b></span><span>Sources <b>'+o.sources+'</b></span></div>'+(o.trend?'<p class="angle">↗ '+E(o.trend)+' '+E(o.traffic)+'</p>':'')+'<div class="src">'+o.links.map(l=>'<a target="_blank" rel="noopener" href="'+E(l.link)+'">'+E(l.source||'Source')+' — '+E(l.title)+'</a>').join('')+'</div></div></article>').join(''):'<div class="err">Aucun faux positif : rien d’assez pertinent pour ce profil.</div>'}catch(e){q('#list').innerHTML='<div class="err">Échec : '+E(e.message)+'</div>'}finally{q('#go').disabled=false}}q('#go').onclick=go;q('#country').onchange=go;q('#lang').onchange=go;q('#site').onchange=go;go();
</script></body></html>`;
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x');res.setHeader('cache-control','no-store');if(u.pathname==='/api/health')return json(res,200,{ok:true,time:new Date().toISOString(),autopublish:{sites:autopublishCfg.sites.map(publicSiteConfig)}});if(u.pathname==='/api/sites')return json(res,200,sites);if(u.pathname==='/api/autopublish/sites')return json(res,200,{policy:autopublishCfg.policy,sites:autopublishCfg.sites.map(publicSiteConfig)});if(req.method==='POST'&&(u.pathname==='/api/autopublish/preflight'||u.pathname==='/api/autopublish/send')){const packet=await jsonBody(req),site=autopublishCfg.sites.find(x=>x.id===packet.siteId);if(!site)return json(res,404,{ok:false,state:'BLOCKED',reason:'unknown_site'});const send=u.pathname.endsWith('/send'),result=await publishPacket(packet,site,{send}),requestId=randomUUID();appendLedger({requestId,source:'api',siteId:packet.siteId,title:packet.title||'',send,result});return json(res,result.ok?200:422,{requestId,...result})}if(u.pathname==='/api/opportunities')return json(res,200,await scan((u.searchParams.get('country')||'FR').toUpperCase(),(u.searchParams.get('lang')||'fr').toLowerCase(),u.searchParams.get('site')||'all'));if(u.pathname==='/'){res.setHeader('content-type','text/html; charset=utf-8');return res.end(html)}res.statusCode=404;res.end('Not found')}catch(e){return json(res,e.message==='payload_too_large'?413:500,{error:e.message})}});server.listen(PORT,()=>console.log('ASTRA NEWS RADAR :'+PORT));
