(function(global){
"use strict";
const VERSION="2.0.0";
const HIGH_CERTAINTY=["100%","garanti","certain","toujours","jamais","aucune erreur","parfaitement","irréfutable","terminé","fini","validé","pass","déployé","fonctionne"];
const PROOF_TERMS=["http 200","status 200","test","tests","log","preuve","evidence","mesure","benchmark","capture","screenshot","commit","curl","playwright","pytest","source","citation","vérifié","verifie","reprodu","sha","hash"];
const COUNTER_TERMS=["contre-test","countertest","red team","false-pass","false pass","faux pass","adversarial","tentative de réfutation","tentative de refutation","counterexample","contre-exemple"];
const REPRO_TERMS=["reprodu","seconde exécution","second run","clean run","fresh run","indépendant","independent","repeat","répété","repete"];
const PRIMARY_TERMS=["source primaire","primary source","documentation officielle","official docs","journal","dataset","mesure brute","raw log"];
function norm(s){return String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function sentences(s){return String(s||"").split(/(?<=[.!?])\s+|\n+/).map(x=>x.trim()).filter(x=>x.length>12)}
function countHits(text,terms){const t=norm(text);return terms.reduce((n,x)=>n+(t.includes(norm(x))?1:0),0)}
function urls(text){return String(text||"").match(/https?:\/\/[^\s)\]}>,]+/g)||[]}
function evidenceLines(text){return String(text||"").split(/\n+/).map(x=>x.trim()).filter(Boolean)}
function classifyClaim(s){const t=norm(s);if(/\b(est|sont|a|ont|fait|fonctionne|deploy|valide|prouve|montre|confirme|atteint)\b/.test(t))return "assertion";if(/\b(devrait|pourrait|peut|probable|semble|suggere)\b/.test(t))return "qualified";return "statement"}
function extractClaims(answer){return sentences(answer).slice(0,40).map((text,i)=>({id:"C"+(i+1),text,type:classifyClaim(text),risk:countHits(text,HIGH_CERTAINTY)}))}
function parseEvidence(text){return evidenceLines(text).slice(0,40).map((raw,i)=>{const u=urls(raw)[0]||null,low=norm(raw);let type=u?"url":/http\s*200|status\s*200/.test(low)?"http":/test|pytest|playwright|spec/.test(low)?"test":/commit|sha|hash|log/.test(low)?"artifact":/source|citation|doc|dataset/.test(low)?"source":"note";return {id:"E"+(i+1),text:raw,type,url:u,independent:/indep|seconde|second|autre source|third.party|externe/.test(low),primary:countHits(raw,PRIMARY_TERMS)>0}})}
function tokenSet(s){return new Set(norm(s).replace(/https?:\/\/\S+/g," ").replace(/[^a-z0-9 ]/g," ").split(/\s+/).filter(x=>x.length>4))}
function overlap(a,b){const A=tokenSet(a),B=tokenSet(b);if(!A.size||!B.size)return 0;let n=0;A.forEach(x=>{if(B.has(x))n++});return n/Math.min(A.size,B.size)}
function linkGraph(claims,evidence){const edges=[];claims.forEach(c=>evidence.forEach(e=>{const o=overlap(c.text,e.text);if(o>=.18)edges.push({from:c.id,to:e.id,weight:+o.toFixed(2)})}));return {nodes:[...claims.map(c=>({id:c.id,kind:"claim",label:c.text.slice(0,72)})),...evidence.map(e=>({id:e.id,kind:"evidence",label:e.text.slice(0,72)}))],edges}}
function passObjective(task){const ok=/pass|partial|fail|crit[eè]re|objectif|succ[eè]s|attendu|acceptance|done when/i.test(task);return {name:"Objective Gate",score:ok?100:45,ok,detail:ok?"Critères de succès détectés.":"Critères PASS/PARTIAL/FAIL insuffisamment explicites."}}
function passEvidence(claims,evidence,graph){const supported=new Set(graph.edges.map(e=>e.from)).size,assertions=claims.filter(c=>c.type==="assertion").length||claims.length||1,coverage=Math.min(1,supported/assertions),typed=evidence.filter(e=>e.type!=="note").length,score=Math.round(coverage*55+Math.min(45,typed*15));return {name:"Evidence Gate",score,ok:score>=70,detail:supported+"/"+assertions+" assertions reliées à des preuves; "+typed+" preuves structurées.",coverage}}
function passRedTeam(answer,evidence){const c=countHits(answer+"\n"+evidence.map(e=>e.text).join("\n"),COUNTER_TERMS),score=Math.min(100,c?70+c*10:20);return {name:"Red Team",score,ok:score>=70,detail:c?c+" signal(aux) de contre-test détecté(s).":"Aucun contre-test explicite."}}
function passFalsePass(answer,evidence){const risk=countHits(answer,HIGH_CERTAINTY),proofs=countHits(answer+"\n"+evidence.map(e=>e.text).join("\n"),PROOF_TERMS)+evidence.length,unsupported=Math.max(0,risk-proofs),score=Math.max(0,Math.min(100,100-risk*8-unsupported*14+(proofs?10:0)));return {name:"False-Pass Hunter",score,ok:score>=70,detail:risk+" marqueur(s) de certitude; "+proofs+" signal(aux) de preuve.",risk,proofs}}
function passRepro(answer,evidence){const t=answer+"\n"+evidence.map(e=>e.text).join("\n"),r=countHits(t,REPRO_TERMS),independent=evidence.filter(e=>e.independent).length,score=Math.min(100,(r?60:15)+independent*20);return {name:"Reproducibility",score,ok:score>=70,detail:r+" signal(aux) de répétition; "+independent+" preuve(s) indépendante(s)."}}
function passIntegrity(evidence){const unique=new Set(evidence.map(e=>norm(e.text))).size,urlsCount=evidence.filter(e=>e.url).length,primary=evidence.filter(e=>e.primary).length,dup=evidence.length-unique,score=Math.max(0,Math.min(100,35+urlsCount*10+primary*15-dup*15+(evidence.length?15:0)));return {name:"Source Integrity",score,ok:score>=70,detail:urlsCount+" URL(s), "+primary+" source(s) primaire(s), "+dup+" doublon(s)."}}
function recommendations(passes,claims,evidence,graph){const out=[];if(!passes[0].ok)out.push("Définir avant exécution les critères exacts de PASS, PARTIAL et FAIL.");if(!passes[1].ok)out.push("Relier les assertions importantes à des preuves précises et vérifiables.");if(!passes[2].ok)out.push("Ajouter une passe Red Team conçue pour réfuter la conclusion.");if(!passes[3].ok)out.push("Réduire les formulations absolues ou leur associer des preuves exécutables.");if(!passes[4].ok)out.push("Répéter le test depuis un état propre avec une méthode ou source indépendante.");if(!passes[5].ok)out.push("Renforcer l'intégrité des sources: URL, source primaire, artefact ou hash.");if(!graph.edges.length&&claims.length&&evidence.length)out.push("Les preuves fournies ne semblent pas sémantiquement reliées aux assertions.");if(!out.length)out.push("Conserver les preuves brutes, l'empreinte du rapport et refaire un contrôle indépendant.");return out}
function audit(input){const task=String(input.task||"").trim(),answer=String(input.answer||"").trim(),evidenceText=String(input.evidence||"").trim(),claims=extractClaims(answer),evidence=parseEvidence(evidenceText),graph=linkGraph(claims,evidence),passes=[passObjective(task),passEvidence(claims,evidence,graph),passRedTeam(answer,evidence),passFalsePass(answer,evidence),passRepro(answer,evidence),passIntegrity(evidence)],weights=[.12,.24,.16,.18,.16,.14];let score=Math.round(passes.reduce((s,p,i)=>s+p.score*weights[i],0));if(answer.split(/\s+/).filter(Boolean).length<25)score=Math.max(0,score-8);if(!evidence.length)score=Math.min(score,44);const hardFail=passes[1].score<25||passes[3].score<25,verdict=hardFail||score<45?"FAIL":score<78?"PARTIAL":"PASS",blockers=passes.filter(p=>!p.ok).map(p=>p.name);return {schema:"mythos-astra-omega/audit@2",engineVersion:VERSION,id:"MAO-"+Date.now().toString(36).toUpperCase(),createdAt:new Date().toISOString(),task,answer,evidenceText,claims,evidence,graph,passes,score,verdict,blockers,recommendations:recommendations(passes,claims,evidence,graph),disclaimer:"Analyse structurelle de fiabilité. Elle ne prouve pas à elle seule la vérité factuelle des affirmations."}}
async function fingerprint(report){const copy=JSON.parse(JSON.stringify(report));delete copy.fingerprint;const bytes=new TextEncoder().encode(JSON.stringify(copy));if(global.crypto&&crypto.subtle){const hash=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("")}let h=2166136261;for(const b of bytes){h^=b;h=Math.imul(h,16777619)}return "fnv1a-"+(h>>>0).toString(16).padStart(8,"0")}
const benchmarkCases=[
{name:"Faux déploiement",task:"Déploie l'app. PASS si build + HTTP 200 + contenu vérifié.",answer:"Terminé. L'application est déployée et fonctionne parfaitement à 100%.",evidence:"",expected:"FAIL"},
{name:"Preuve faible",task:"Confirme que la migration est correcte.",answer:"La migration semble correcte et les tests passent.",evidence:"test local PASS",expected:"PARTIAL"},
{name:"Audit robuste",task:"PASS si tests e2e, HTTP 200, contre-test et seconde vérification indépendante réussissent.",answer:"Les tests e2e passent. Un contre-test Red Team a été exécuté. Résultat reproductible sur un second run indépendant.",evidence:"https://example.com/health HTTP 200 source primaire\nPlaywright test PASS indépendant\nsecond run reproduit commit SHA abc123",expected:"PASS"},
{name:"Certitude sans source",task:"Évalue l'affirmation.",answer:"C'est certain, garanti et irréfutable. Aucune erreur possible.",evidence:"",expected:"FAIL"},
{name:"Logs seuls",task:"Valider l'API avec critères PASS/PARTIAL/FAIL.",answer:"Les logs indiquent que l'API répond.",evidence:"log serveur: request complete",expected:"PARTIAL"},
{name:"Sources sans contre-test",task:"PASS si deux sources concordent et un contre-test est exécuté.",answer:"Deux sources confirment le résultat.",evidence:"https://example.org/source documentation officielle\nhttps://example.net/source2 source primaire indépendante",expected:"PARTIAL"},
{name:"Reproduction forte",task:"PASS si mesure répétée et source indépendante.",answer:"Mesure vérifiée et reproduite sur une seconde exécution indépendante. Red Team sans réfutation.",evidence:"dataset source primaire\nsecond run indépendant test PASS\ncontre-test adversarial PASS",expected:"PASS"},
{name:"Affirmation courte",task:"Vérifier.",answer:"Ça marche.",evidence:"",expected:"FAIL"}];
function runBenchmark(){const rows=benchmarkCases.map(c=>{const r=audit(c);return {name:c.name,expected:c.expected,actual:r.verdict,score:r.score,ok:c.expected===r.verdict}});const passed=rows.filter(x=>x.ok).length;return {rows,passed,total:rows.length,rate:Math.round(passed/rows.length*100)}}
global.MythosEngine={VERSION,audit,fingerprint,runBenchmark,benchmarkCases};
})(window);