
import { createServer } from "node:http";
import { readFileSync } from "node:fs";
const SITE="https://eldiariodelcibao.com";
const PORT=Number(process.env.PORT||3000);
const content=JSON.parse(readFileSync(new URL("./data/content.json",import.meta.url),"utf8"));
const historicRecords=JSON.parse(readFileSync(new URL("./data/historic-routes.json",import.meta.url),"utf8"));
const pages=content.pages||[], currentNews=content.currentNews||[], trustPages=content.trustPages||[];
const historicMap=new Map(historicRecords.map(x=>[x.path,x]));
function e(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function words(s=""){return String(s).trim().split(/\s+/).filter(Boolean).length}
function pageWords(x){return words(x.sections?(x.sections||[]).flatMap(s=>[s[0],...(s[1]||[])]).join(" "):(x.b||[]).join(" "))}
function newsWords(x){return words((x.sections||[]).flatMap(s=>s[1]||[]).join(" "))}
function slug(s=""){return String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)}
function mediaImg(x){return "/media/"+slug(x.title||x.t||"archivo-historico")+".svg"}
function titleFromPath(path){const leaf=decodeURIComponent(String(path).split("/").pop()||"archivo").replace(/\.html?$/i,"").replace(/[_-]+/g," ").replace(/\s+/g," ").trim();return leaf?leaf.charAt(0).toUpperCase()+leaf.slice(1):"Archivo histórico"}
function yearFromPath(path){const m=String(path).match(/^\/(20\d{2})\//);return m?m[1]:"Archivo"}
const css=":root{--ink:#151515;--muted:#696969;--line:#ddd7ca;--paper:#fffdf8;--red:#a31217;--card:#fff}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font-family:Georgia,serif}a{color:inherit}a:focus-visible{outline:3px solid #111;outline-offset:3px}header{background:#fff;border-bottom:1px solid var(--line)}.top{max-width:1180px;margin:auto;padding:16px 20px;display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap}.brand{font-size:31px;font-weight:800;text-decoration:none;line-height:1}.brand span{color:var(--red)}nav{display:flex;gap:8px;flex-wrap:wrap;font:700 14px Arial,sans-serif}nav a{padding:12px 10px;border-radius:6px;text-decoration:none;min-height:44px;display:flex;align-items:center}nav a:hover{background:#f3efe7}main{max-width:1180px;margin:auto;padding:34px 20px 70px}.article{max-width:820px;margin:auto}.hero{border-bottom:1px solid var(--line);padding:28px 0 32px;margin-bottom:30px}.k{font:800 12px Arial,sans-serif;text-transform:uppercase;letter-spacing:.14em;color:var(--red)}h1{font-size:clamp(40px,6vw,72px);line-height:1.02;margin:10px 0 18px}h2{font-size:30px;line-height:1.15;margin:40px 0 12px}h3{font-size:23px}p{font-size:20px;line-height:1.68;margin:0 0 20px}.deck{font-size:24px;color:#444}.meta{font:14px/1.5 Arial,sans-serif;color:var(--muted);margin:18px 0}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.card{display:block;background:var(--card);border:1px solid var(--line);padding:14px;text-decoration:none}.card h3{margin:10px 0}.card p{font-size:16px;line-height:1.5;color:#444}.card img,.feature{width:100%;height:auto;display:block;aspect-ratio:16/9;object-fit:cover;border:1px solid var(--line);background:#f7f0e3}.notice{background:#fff3d6;border:1px solid #dfc58a;padding:16px;margin:22px 0;font:15px/1.55 Arial,sans-serif}.sourcebox{margin-top:36px;padding:18px;border-top:2px solid var(--ink);background:#fff}.sourcebox ul{font:16px/1.6 Arial,sans-serif;padding-left:20px}footer{border-top:1px solid var(--line);padding:28px 20px;background:#fff;font:14px/1.6 Arial,sans-serif;color:#666}.foot{max-width:1180px;margin:auto;display:flex;gap:16px;flex-wrap:wrap;justify-content:space-between}.footnav{display:flex;gap:12px;flex-wrap:wrap}@media(max-width:820px){.grid{grid-template-columns:1fr}.top{align-items:flex-start}.deck{font-size:21px}p{font-size:18px}h2{font-size:27px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}";
function nav(){return '<header><div class="top"><a class="brand" href="/"><span>El Diario</span> del Cibao</a><nav aria-label="Principal"><a href="/cibao/">Cibao</a><a href="/santiago/">Santiago</a><a href="/economia-del-cibao/">Economía</a><a href="/turismo-en-el-cibao/">Turismo</a><a href="/archivo/">Archivo</a></nav></div></header>'}
function footer(){return '<footer><div class="foot"><div>© 2026 El Diario del Cibao · Santiago y región norte</div><div class="footnav"><a href="/nosotros/">Nosotros</a><a href="/politica-editorial/">Política editorial</a><a href="/fuentes-y-correcciones/">Fuentes y correcciones</a><a href="/contacto/">Contacto</a><a href="/privacidad/">Privacidad</a></div></div></footer>'}
function shell(o){const robots=o.robots||"index,follow,max-image-preview:large,max-snippet:-1";return '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(o.title)+' | El Diario del Cibao</title><meta name="description" content="'+e(o.desc)+'"><meta name="robots" content="'+robots+'"><link rel="canonical" href="'+SITE+o.path+'"><meta property="og:site_name" content="El Diario del Cibao"><meta property="og:title" content="'+e(o.title)+'"><meta property="og:description" content="'+e(o.desc)+'"><meta property="og:url" content="'+SITE+o.path+'">'+(o.extra||"")+'<style>'+css+'</style></head><body>'+nav()+o.body+footer()+'</body></html>'}
function secHtml(arr){return (arr||[]).map(s=>'<section><h2>'+e(s[0])+'</h2>'+(s[1]||[]).map(x=>'<p>'+e(x)+'</p>').join("")+'</section>').join("")}
function pageRobots(x){return pageWords(x)>=1500?"index,follow,max-image-preview:large,max-snippet:-1":"noindex,follow,max-image-preview:large"}
function renderPage(x){const img=mediaImg(x);const notice=x.a&&pageWords(x)<1500?'<div class="notice"><b>Archivo histórico en reconstrucción.</b> Esta ruta está confirmada, pero permanece noindex hasta superar el gate editorial de 1.500 palabras con evidencia histórica verificable.</div>':"";const schema=JSON.stringify({"@context":"https://schema.org","@type":x.a?"Article":"WebPage","headline":x.t,"description":x.d,"mainEntityOfPage":SITE+x.p,"dateModified":"2026-10-05","publisher":{"@type":"Organization","name":"El Diario del Cibao","url":SITE}});const body='<main><article class="article"><div class="k">'+e(x.s)+'</div><h1>'+e(x.t)+'</h1><p class="deck">'+e(x.d)+'</p><div class="meta">'+(x.a?"Archivo histórico · reconstrucción en curso":"Actualizado: 5 de octubre de 2026")+'</div><img class="feature" src="'+img+'" width="1200" height="675" alt="'+e(x.t)+'">'+notice+(x.sections?secHtml(x.sections):(x.b||[]).map((p,i)=>(i===1?'<h2>Contexto y relevancia</h2>':i===3?'<h2>Continuidad editorial</h2>':'')+'<p>'+e(p)+'</p>').join(""))+(x.related&&x.related.length?'<section><h2>Más sobre este tema</h2><ul>'+x.related.map(r=>'<li><a href="'+e(r[0])+'">'+e(r[1])+'</a></li>').join("")+'</ul></section>':"")+(x.sources&&x.sources.length?'<aside class="sourcebox"><h2>Fuentes y referencias</h2><ul>'+x.sources.map(s=>'<li><a href="'+e(s[1])+'" target="_blank" rel="noopener">'+e(s[0])+'</a></li>').join("")+'</ul></aside>':"")+'</article></main>';return shell({title:x.t,desc:x.d,path:x.p,body,robots:pageRobots(x),extra:'<meta property="og:image" content="'+SITE+img+'"><script type="application/ld+json">'+schema.replace(/</g,"\\u003c")+'</script>'})}
function renderNews(n){const img=mediaImg(n),wc=newsWords(n);const sources='<aside class="sourcebox"><h2>Fuentes</h2><ul>'+(n.sources||[]).map(s=>'<li><a href="'+e(s[1])+'" target="_blank" rel="noopener">'+e(s[0])+'</a></li>').join("")+'</ul></aside>';const schema=JSON.stringify({"@context":"https://schema.org","@type":"NewsArticle","headline":n.title,"description":n.description,"datePublished":n.published,"dateModified":n.published,"mainEntityOfPage":SITE+n.path,"image":[SITE+img],"author":{"@type":"Organization","name":"Redacción El Diario del Cibao"},"publisher":{"@type":"NewsMediaOrganization","name":"El Diario del Cibao","url":SITE}});const robots=wc>=1500?"index,follow,max-image-preview:large,max-snippet:-1":"noindex,follow,max-image-preview:large";const body='<main><article class="article"><div class="k">'+e(n.section)+'</div><h1>'+e(n.title)+'</h1><p class="deck">'+e(n.description)+'</p><div class="meta">Publicado: 5 de octubre de 2026 · Redacción El Diario del Cibao · '+wc.toLocaleString("es-DO")+' palabras</div><img class="feature" src="'+img+'" width="1200" height="675" alt="'+e(n.title)+'">'+secHtml(n.sections)+sources+'</article></main>';return shell({title:n.title,desc:n.description,path:n.path,body,robots,extra:'<meta property="og:image" content="'+SITE+img+'"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="'+SITE+img+'"><script type="application/ld+json">'+schema.replace(/</g,"\\u003c")+'</script>'})}
function renderTrust(t){return shell({title:t.title,desc:t.description,path:t.path,body:'<main><article class="article"><div class="k">'+e(t.section)+'</div><h1>'+e(t.title)+'</h1><p class="deck">'+e(t.description)+'</p>'+secHtml(t.sections)+'</article></main>'})}
function renderHistoric(r){const title=titleFromPath(r.path),year=yearFromPath(r.path);return shell({title,desc:"Ruta histórica de El Diario del Cibao en proceso de reconstrucción.",path:r.path,robots:"noindex,follow,max-image-preview:large",body:'<main><article class="article"><div class="k">Archivo '+e(year)+'</div><h1>'+e(title)+'</h1><img class="feature" src="/media/archivo-historico.svg" width="1200" height="675" alt="Archivo histórico de El Diario del Cibao"><div class="notice"><b>URL histórica verificada.</b> Esta dirección forma parte del inventario Wayback del antiguo sitio. Permanece noindex hasta reconstruir el contenido con capturas y fuentes suficientes para superar el gate de 1.500 palabras.</div><h2>Estado de restauración</h2><p>La ruta exacta ha sido recuperada y ya no se considera una URL desconocida. El siguiente paso es reconstruir el artículo original sin copiar el texto histórico y sin convertir el título en una fuente factual por sí solo.</p></article></main>'})}
function home(){const news=currentNews.map(n=>'<a class="card" href="'+n.path+'"><img src="'+mediaImg(n)+'" width="1200" height="675" alt="'+e(n.title)+'"><div class="k">'+e(n.section)+'</div><h3>'+e(n.title)+'</h3><p>'+e(n.description)+'</p></a>').join("");const hubs=pages.filter(x=>!x.a).map(x=>'<a class="card" href="'+x.p+'"><img src="'+mediaImg(x)+'" width="1200" height="675" alt="'+e(x.t)+'"><div class="k">'+e(x.s)+'</div><h3>'+e(x.t)+'</h3><p>'+e(x.d)+'</p></a>').join("");const body='<main><section class="hero"><div class="k">Santiago · Cibao · República Dominicana</div><h1>El Diario del Cibao</h1><p class="deck">Actualidad verificable y reconstrucción del archivo histórico 2011–2018.</p></section><h2>Actualidad</h2><div class="grid">'+news+'</div><h2>Guías y contexto</h2><div class="grid">'+hubs+'</div></main>';return shell({title:"Noticias del Cibao y Santiago",desc:"Noticias, contexto y archivo histórico de Santiago y el Cibao.",path:"/",body})}
function archiveIndex(){const years={};for(const r of historicRecords){const y=yearFromPath(r.path);years[y]=(years[y]||0)+1}const stats=Object.entries(years).sort().map(([y,n])=>'<div class="card"><div class="k">'+e(y)+'</div><h3>'+n.toLocaleString("es-DO")+' rutas</h3><p>URLs Wayback exactas identificadas para reconstrucción progresiva.</p></div>').join("");return shell({title:"Archivo histórico",desc:"Inventario de las URLs históricas de El Diario del Cibao.",path:"/archivo/",body:'<main><section class="hero"><div class="k">Wayback 2011–2018</div><h1>Archivo histórico reconstruido por rutas</h1><p class="deck">'+historicRecords.length.toLocaleString("es-DO")+' caminos históricos reconocidos. Solo las páginas con contenido verificado y suficiente entran en indexación.</p></section><div class="grid">'+stats+'</div></main>'})}
function sitemap(){const urls=["/"];for(const n of currentNews)if(newsWords(n)>=1500)urls.push(n.path);for(const x of pages)if(pageWords(x)>=1500)urls.push(x.p);for(const t of trustPages)urls.push(t.path);return '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+[...new Set(urls)].map(u=>'<url><loc>'+SITE+u+'</loc><lastmod>2026-10-05</lastmod></url>').join("")+'</urlset>'}
function newsSitemap(){return '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">'+currentNews.filter(n=>newsWords(n)>=1500).map(n=>'<url><loc>'+SITE+n.path+'</loc><news:news><news:publication><news:name>El Diario del Cibao</news:name><news:language>es</news:language></news:publication><news:publication_date>'+e(n.published)+'</news:publication_date><news:title>'+e(n.title)+'</news:title></news:news></url>').join("")+'</urlset>'}
function rss(){return '<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>El Diario del Cibao</title><link>'+SITE+'</link><description>Actualidad de Santiago y el Cibao</description><language>es-do</language>'+currentNews.filter(n=>newsWords(n)>=1500).map(n=>'<item><title>'+e(n.title)+'</title><link>'+SITE+n.path+'</link><guid>'+SITE+n.path+'</guid><pubDate>'+new Date(n.published).toUTCString()+'</pubDate><description>'+e(n.description)+'</description></item>').join("")+'</channel></rss>'}
function svgFor(x){const title=x?.image?.[0]||x?.title||x?.t||"Archivo histórico",sub=x?.image?.[1]||x?.section||x?.s||"El Diario del Cibao";return '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="675" viewBox="0 0 1200 675"><rect width="1200" height="675" fill="#f7f0e3"/><rect width="1200" height="22" fill="#a31217"/><circle cx="985" cy="315" r="160" fill="#ead9b7"/><text x="985" y="365" text-anchor="middle" font-family="Georgia" font-size="150" fill="#a31217">◆</text><text x="72" y="105" font-family="Arial" font-size="28" font-weight="700" fill="#a31217">EL DIARIO DEL CIBAO</text><text x="72" y="250" font-family="Georgia" font-size="54" font-weight="700" fill="#151515">'+e(String(title).slice(0,38))+'</text><text x="72" y="330" font-family="Georgia" font-size="32" fill="#333">'+e(String(sub).slice(0,54))+'</text><text x="72" y="560" font-family="Arial" font-size="24" fill="#666">Santiago · Cibao · República Dominicana</text></svg>'}
function headers(type,cache="public, max-age=300"){return {"content-type":type,"cache-control":cache,"x-content-type-options":"nosniff","referrer-policy":"strict-origin-when-cross-origin","content-security-policy":"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'"}}
createServer((req,res)=>{const host=(req.headers.host||"").split(":")[0],u=new URL(req.url||"/","http://"+(host||"localhost")),p=u.pathname;if(host==="www.eldiariodelcibao.com"){res.writeHead(308,{location:SITE+p+u.search});return res.end()}let status=200,type="text/html; charset=utf-8",cache="public, max-age=300",body="";if(p==="/health"){type="application/json; charset=utf-8";cache="no-store";body=JSON.stringify({ok:true,service:"eldiariodelcibao-web",version:"repo-2026-10-05",historicRoutes:historicRecords.length,currentNews:currentNews.length,news1500:currentNews.filter(n=>newsWords(n)>=1500).length})}else if(p==="/robots.txt"){type="text/plain; charset=utf-8";cache="public, max-age=3600";body="User-agent: *\nAllow: /\nSitemap: "+SITE+"/sitemap.xml\nSitemap: "+SITE+"/news-sitemap.xml\n"}else if(p==="/sitemap.xml"){type="application/xml; charset=utf-8";body=sitemap()}else if(p==="/news-sitemap.xml"){type="application/xml; charset=utf-8";body=newsSitemap()}else if(p==="/feed.xml"){type="application/rss+xml; charset=utf-8";body=rss()}else if(p==="/archive-manifest.json"){type="application/json; charset=utf-8";body=JSON.stringify({count:historicRecords.length,routes:historicRecords})}else if(p.startsWith("/media/")&&p.endsWith(".svg")){type="image/svg+xml; charset=utf-8";cache="public, max-age=86400";const sl=p.slice(7,-4),x=currentNews.find(n=>slug(n.title)===sl)||pages.find(x=>slug(x.t)===sl)||trustPages.find(x=>slug(x.title)===sl)||{title:"Archivo histórico",section:"El Diario del Cibao"};body=svgFor(x)}else if(p==="/"){body=home()}else if(p==="/archivo"||p==="/archivo/"){body=archiveIndex()}else{const n=currentNews.find(x=>x.path===p||x.path.replace(/\/$/,"")===p.replace(/\/$/,"")),t=trustPages.find(x=>x.path===p||x.path.replace(/\/$/,"")===p.replace(/\/$/,"")),x=pages.find(x=>x.p===p||x.p.replace(/\/$/,"")===p.replace(/\/$/,"")),h=historicMap.get(p);if(n)body=renderNews(n);else if(t)body=renderTrust(t);else if(x)body=renderPage(x);else if(h)body=renderHistoric(h);else{status=404;cache="no-store";body=shell({title:"Página no encontrada",desc:"La página solicitada no existe.",path:p,body:'<main><section class="hero"><div class="k">404</div><h1>Página no encontrada</h1><p class="deck">La dirección no pertenece al archivo histórico identificado ni a la publicación actual.</p></section></main>',robots:"noindex,nofollow"})}}res.writeHead(status,headers(type,cache));res.end(body)}).listen(PORT,"0.0.0.0",()=>console.log("ELDIARIO_READY",JSON.stringify({port:PORT,historicRoutes:historicRecords.length,currentNews:currentNews.length,news1500:currentNews.filter(n=>newsWords(n)>=1500).length})));
