import assert from "node:assert/strict";
import {audit} from "./src/engine.mjs";
import {getPolicy} from "./src/policies.mjs";
const strict=getPolicy("strict");
const fail=audit({task:"PASS seulement si une preuve indépendante existe.",answer:"C'est garanti à 100%, tout fonctionne parfaitement.",evidence:[],verifiedEvidence:[],policy:strict});
assert.equal(fail.verdict,"FAIL");
const pass=audit({task:"PASS si tests, contre-test et second run indépendant sont présents.",answer:"Tests validés. Red Team exécutée. Résultat reproduit sur un second run indépendant.",evidence:[{text:"Playwright test PASS"},{text:"second run indépendant SHA abc123"},{text:"contre-test adversarial"}],verifiedEvidence:[{ok:true,status:"PASS"}],policy:strict});
assert.equal(pass.verdict,"PASS");
assert.match(pass.fingerprint,/^[a-f0-9]{64}$/);
console.log(JSON.stringify({fail:{verdict:fail.verdict,score:fail.score},pass:{verdict:pass.verdict,score:pass.score},fingerprint:pass.fingerprint.slice(0,16)},null,2));
console.log("EVIDORIX_SELFTEST=PASS");
